### ISSUE TITLE
Add abstraction for filter state lookup

### ISSUE THREAD

**Issue by iffyio** [googleforgames/quilkin#375]
Some filters would like to store state keyed by packet information like source address, this is useful for #374 and #5 
we would like to add e.g a key-value map that is smart enough to expire items from the map after the session duration timeout (similar to our session map impl)

**Comment by gilesheron** [comment]
yes, feels like the need for state tracking potentially only applies for filters that "route" (where you only want to make the decision once per flow) and not to filters that modify packet contents.  So that fits with #104.

will be interested to see what you decide - I'm still hoping to implement that load balancer mode that calls out to an external API, and that really does nee to be once per flow.
