### ISSUE TITLE
Changing dynamic metadata from `Any`.

### ISSUE THREAD

**Issue by XAMPPRocky** [googleforgames/quilkin#433]
Currently, out metadata type is `Box<std::any::Any + Send>`, which allows for it to be downcast to a concrete type. This is suitable when both the creator and reader know the concrete type of the metadata. However there are more cases where we want to be able to do something with the metadata without knowing the concrete type.

One example of this is if you where to have dynamic or scripted filters, another case is attempting to implement the `quilkin.match` filter described in #401. In order to be able to branch, we need to be able to compare the values in the config with the values in the metadata map, without knowing really knowing the concrete type. So we need a common type that can be compared

I'd like to instead propose that we switch from using `Box<std::any::Any>` to `serde_yaml::Value` as the base metadata type. This does potentially add a serialisation step, however we should discourage ourselves and users from serialising simple metadata, and to instead create `serde_yaml::Values` directly.

**Comment by markmandel** [comment]
I can see this making a lot of sense, especially with the dynamic or scripted filters, where it will be harder to have shared types between externally loaded systems.

Putting some restrictions on what data is possible makes things easier for us to manage, and I don't think will restrict usage in any major way. Also, serde_yaml::Value has a nicer API for runtime introspection, which could be handy for all kinds of debugging and monitoring.

The only possible thought I could have, is does it make any more sense to have our own type, similar to serde_yaml::Value (probably with a very close API)? I can think of two reasons for this:

1. We remove the whole serialisation equation, because our API wouldn't allow it
2. We could focus on data types that were common to our use cases. For example, the TokenRouter (and related) uses a `Vec<u8>` to store the token. I can see a byte array being very useful across a number of Filters, but with `serde_yaml::Value`, this would have to be represented by a `Sequence<Number>` which is  a tad unwieldy when trying to compare it to `Vec<u8>` that is more common in our system.

It's more work, but it might give us much more control. WDYT?

**Comment by XAMPPRocky** [comment]
Yeah, I do think having our own type makes sense and it would tie into #346 where then we can take our internal representation and convert into YAML, Protobuf, JSON, etc.

**Comment by markmandel** [comment]
> ...it would tie into #346 where then we can take our internal representation and convert into YAML, Protobuf, JSON, etc.

oh yeah, that's also a really good point too 👍🏻
