### ISSUE TITLE
`EndpointAddress` should be resolved once

### ISSUE THREAD

**Issue by Jake-Shadle** [googleforgames/quilkin#949]
Currently we do a (cached) DNS lookup on every proxy for every non-socket address endpoint https://github.com/googleforgames/quilkin/blob/6badc240d5257fceda436a3661d6e43b93fa387f/src/components/proxy/packet_router.rs#L234. To me this doesn't really make sense, and really the relay should do the resolution of addresses so that proxies only ever have to deal with resolved socket addresses.

**Comment by XAMPPRocky** [comment]
> To me this doesn't really make sense, and really the relay should do the resolution of addresses so that proxies only ever have to deal with resolved socket addresses.

I don't think that makes sense, because we can't rely that it always resolves to the same IP address. One of the main reasons we support DNS is for AWS, and the IPs for pod addresses change frequently, and we want to send where it resolves to in that moment, not at the moment it was visible to relay. Also you might get a different IP address when resolving from the proxy than from the relay, because DNS can be setup so that it resolves to the closest pathway, and that could be a very different path for the relay and the proxy because they could be on different sides of the world.

It's also important to remember that we support more setups than just relay, if you're running just the proxy, you want it to be able to resolve DNS entries on its own.

**Comment by Jake-Shadle** [comment]
Ahh ok
