### ISSUE TITLE
Make filters static dispatch?

### ISSUE THREAD

**Issue by Jake-Shadle** [googleforgames/quilkin#951]
Currently all filters are dynamically created and dispatched, which makes sense since one can also add their own filters as seen in https://github.com/googleforgames/quilkin/tree/main/examples/quilkin-filter-example, but....does it actually make sense to support custom filters? This is an open source project, it feels like it would be cleaner and simpler to remove the support for custom filters and just have a statically dispatchable enum of all of the filters in quilkin. If users want their own filter they can just add it to the codebase with all of the others, meaning others with the same/similar needs get the benefits.

**Comment by XAMPPRocky** [comment]
> If users want their own filter they can just add it to the codebase with all of the others, meaning others with the same/similar needs get the benefits.

Not if they add a filter that does bespoke logic that integrates with a proprietary system or proprietary logic that they can't share.

Though I do somewhat agree, and I have for awhile said that we should move custom user filters to be WASM based, because that would be a lot easier for users to be able to build a module in whatever they want in just a module, rather than needing to ship a custom version.

However I'm not sure either would allow for us to be able to use static dispatch because the filter chain, would still always be dynamic and created from configuration like a yaml file or a configmap, as we need to allow people to setup a custom filter chain of logic for their needs and some filters like `Match` are able to reference other filters in that configuration.
